# -*- coding: utf-8 -*-
"""Week 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ab4niGRa2Ywgc1FWiVFZ1FIZVc5Ycclj
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/studentperformance_preprocessed.csv")

print(df.head())

print(df.shape)

plt.figure(figsize=(10,6))

sns.barplot(
    x='parental level of education',
    y='math score',
    hue='lunch',
    data=df
)

plt.title('Average Math Score by Parental Education and Lunch Type')
plt.xlabel('Parental Education Level')
plt.ylabel('Average Math Score')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    x='test preparation course',
    y='math score',
    data=df
)

plt.title('Math Score Based on Test Preparation')
plt.xlabel('Test Preparation Course')
plt.ylabel('Math Score')
plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(
    x='math score',
    y='reading score',
    data=df
)

plt.title('Math Score vs Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(
    x='math score',
    y='writing score',
    data=df
)

plt.title('Math Score vs Writing Score')
plt.xlabel('Math Score')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(8,5))

corr = df[['math score', 'reading score', 'writing score']].corr()

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Between Math, Reading and Writing Scores')
plt.show()

corr = df[['math score', 'reading score', 'writing score']].corr()

print(corr)