# -*- coding: utf-8 -*-
"""week 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1yLZG0YIGHWP7uYTtOdxVxHBhx6bjBd
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/healthcare_dataset.csv")

df.head()

df.columns

df.shape

df.dtypes

df.isnull()

df.isnull().sum()

df['Medical_Code'].isnull().sum()

df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Admission_Date']

df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])
df['Discharge_Date']

df['Admission_Type'].value_counts()

df['Admission_Type'] = (
    df['Admission_Type']
    .str.lower()
)

df.describe()

df["Admission"]

df["Hospital_Stay_Days"]=(df["Discharge_Date"]-df["Admission_Date"]).dt.days
df["Hospital_Stay_Days"].head()

df["Billing_Amount"].describe()

