# -*- coding: utf-8 -*-
"""WEEK 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZqIbMte-FavDYVhqVVCsvyQX4cMDVOY
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance.csv")

df.head()

df.columns

df.dtypes

df.info()

categorical_features = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
]

for col in categorical_features:
  df[col] = df[col].str.strip().str.title()

df[['gender','race/ethnicity',]]

score_columms = [
    'math score',
    'reading score',
    'writing score'
]

print("\nStatistical Measures:")

for column in score_columms:
  print(f"\n{column}")
  print("Mean:",df[column].mean())
  print("Median:", df[column].median())
  print("Standard Deviation:", df[column].std())
  print("Q1:", df[column].quantile(0.25))
  print("Q2:", df[column].quantile(0.50))
  print("Q3:", df[column].quantile(0.75))