# -*- coding: utf-8 -*-
"""Week 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM_p0KslsaYw0IvT8utX1QdYvLt34cq5
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/healthcare_dataset.csv")

df.head()

df.columns

df.columns

df.dtypes

df.isnull()

df.isnull().sum()

df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

df["stay Duration"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days
df.head()

billing = df.groupby(["Medical Condition","Insurance Provider"])["Billing Amount"].sum()

data = df.groupby(
    ["Medical Condition", "Insurance Provider"]
)["Billing Amount"].mean().unstack()

# Bar chart
data.plot(
    kind="bar",
    stacked=True,
    figsize=(12, 6)
)

plt.title("Average Billing Amount by Medical Condition and Insurance Provider")
plt.xlabel("Medical Condition")
plt.ylabel("Average Billing Amount")
plt.xticks(rotation=45)
plt.legend(title="Insurance Provider")

plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x="Medical Condition",
    y="Billing Amount"
)

plt.title("Billing Amount Distribution by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x="Insurance Provider",
    y="Billing Amount"
)

plt.title("Billing Amount Distribution by Insurance Provider")
plt.xlabel("Insurance Provider")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df['Admission'] = df['Date of Admission'].dt.month

plt.figure(figsize=(12,6))
Monthly_Admission = df.groupby('Admission').size()
Monthly_Admission.plot(kind="line",marker="o")

plt.title("Monthly Patient Admission")
plt.xlabel("Month")
plt.ylabel("Number of Admissions")
plt.xticks(rotation=45)
plt.grid()

correlation_matrix = df[["Age","stay Duration","Billing Amount"]].corr()
correlation_matrix

sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()