# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvBwfCuNs43AJhV55guleUO0xbckomJ0
"""

import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")

df.head()

df.tail()

df.info()

df.dtypes

df.columns

df=df.drop_duplicates()

df["Open"].mean()

df["Close"].mean()

df["High"].max()

df["Low"].min()